# Generated by Django 5.2.1 on 2025-05-24 02:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengiriman',
            old_name='alamat',
            new_name='alamat_penerima',
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='alamat_pengirim',
            field=models.TextField(default='Toko E-Commerce, Surabaya'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 24, 2, 46, 12, 135819, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='ekspedisi',
            field=models.CharField(choices=[('jne', 'JNE'), ('pos', 'Pos Indonesia'), ('tiki', 'TIKI'), ('j&t', 'J&T Express'), ('sicepat', 'SiCepat'), ('anteraja', 'AnterAja'), ('ninja', 'Ninja Express'), ('gosend', 'GoSend'), ('grab', 'GrabExpress')], default='jne', max_length=20),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='estimasi_hari',
            field=models.IntegerField(default=3, help_text='Estimasi pengiriman dalam hari'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='no_resi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='tanggal_kirim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='tanggal_terkirim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='berat',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Berat dalam kg', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='pengiriman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.pengiriman'),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Sedang Diproses'), ('shipped', 'Dikirim'), ('in_transit', 'Dalam Perjalanan'), ('out_for_delivery', 'Keluar untuk Pengiriman'), ('delivered', 'Terkirim'), ('failed', 'Gagal Kirim'), ('returned', 'Dikembalikan')], default='pending', max_length=50),
        ),
    ]
