# Generated by Django 5.2.1 on 2025-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_alamat_pengiriman_alamat_penerima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
    ]
