# Generated by Django 5.2.2 on 2025-06-05 19:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='rating_rata_rata',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='UlasanProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Peringkat 1 (terburuk) hingga 5 (terbaik)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal_ulasan', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.buyer')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produk')),
            ],
            options={
                'unique_together': {('produk', 'buyer')},
            },
        ),
    ]
