# Generated by Django 5.2.2 on 2025-06-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_produk_rating_rata_rata_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='GambarProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(help_text='Unggah gambar detail produk', upload_to='produk_images/details/')),
                ('alt_text', models.CharField(blank=True, help_text='Teks alternatif untuk gambar (SEO)', max_length=255)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_tambahan', to='ecommerce.produk')),
            ],
            options={
                'verbose_name': 'Gambar Produk',
                'verbose_name_plural': 'Gambar-gambar Produk',
            },
        ),
    ]
