# Generated by Django 5.2.2 on 2025-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_kategori_alter_produk_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_profil',
            field=models.ImageField(blank=True, default='foto_profil/default.png', null=True, upload_to='foto_profil/'),
        ),
    ]
