# Generated by Django 5.2.2 on 2025-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_user_foto_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100, verbose_name='Kabupaten/Kota')),
                ('kecamatan', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=0, help_text='Biaya dalam Rupiah', max_digits=10)),
            ],
            options={
                'verbose_name': 'Ongkos Kirim',
                'verbose_name_plural': 'Daftar Ongkos Kirim',
                'unique_together': {('provinsi', 'kabupaten_kota', 'kecamatan')},
            },
        ),
    ]
